(define (square x)
    (* x x))
(define (average x y)
    (/ (+ x y) 2))
(define (absolute x)
    (if (< x 0)
	(- x)
	x))
(define (improve guess x)
    (average guess (/ x guess)))
(define (good-enough? guess x)
    (< (absolute (- (square guess) x))
       .001))
(define (try guess x)
    (if (good-enough? guess x)
	guess
	(try (improve guess x) x)))
(define (myroot x) (try 1 x))
